# MySQL Database Connection
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/wind
    username: root # your mysql username
    password: # you can provide your mysql password
